### ISSUE TITLE
Make footer links bold

### ISSUE THREAD

**Issue by 0xadamm** [0xadamm/tronix_homepage_html_shared#11]
![image](https://github.com/0xadamm/tronix_homepage_html_shared/assets/94600225/a020193a-741a-47e2-a767-9e60492a1ed1)

**Comment by 0xadamm** [comment]
Inject this into vodlix template customizer
``` css
.ftLink {
    font-weight: bold;
}
```
